from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "models": (
        "FitResult",
        "Candidate",
        "CandidatePrefit",
        "CandidateEvidence",
        "Detection",
        "RestorationDiagnostics",
        "RestorationResult",
        "PatchContext",
        "BodySourceResult",
        "BackendUnavailableError",
        "WatermarkRemoverConfig",
        "_pad_bbox",
        "bbox_iou",
        "_is_center_contained",
    ),
    "templates": (
        "ResizedTemplate",
        "TemplateBundle",
        "load_template",
        "load_templates",
        "_template_image_candidates",
        "list_input_images",
        "load_image_rgb",
        "save_image_rgb",
        "save_image_like",
        "_rgb_to_gray",
        "_estimate_template_background",
        "build_template_support_mask",
        "_binary_mask",
        "_min_component_area",
        "_close_mask",
        "_odd_kernel_size",
        "_clean_mask",
        "_remove_small_mask_components",
        "_filled_support_holes",
        "_compute_edge_map",
        "_color_deviation",
    ),
    "lama": (
        "_LAMA_CACHE",
        "_run_lama",
        "build_simple_lama_runner",
    ),
    "debug_render": (
        "normalize_debug_map",
        "_normalize_debug_mask",
        "_normalize_residual_debug_map",
        "_normalize_change_debug_map",
        "_json_safe_debug_value",
        "render_debug_overlay",
        "_debug_overlay_label",
        "render_debug_map",
    ),
    "masking": (
        "build_detection_mask",
        "restore_with_mask",
        "restore_original_regions",
        "_restore_lama_patch",
        "_build_lama_mask",
        "_run_lama_with_context",
        "_build_restoration_result",
        "_compute_restoration_diagnostics",
        "_build_patch_context",
        "_aligned_template_for_patch",
        "_template_visible_body_mask",
        "_template_body_source_mask",
        "_seed_connected_mask",
        "_build_lama_mask_body",
        "_build_contour_mask_body",
        "_build_mask_body",
        "_mask_component_count",
        "_soft_expand_mask",
        "_needs_sparse_chromatic_confidence_gate",
        "_has_sparse_chromatic_color_edge_evidence",
        "_has_sparse_chromatic_spatial_evidence",
        "_template_has_solid_dark_region",
        "_solid_dark_template_match_metrics",
        "_template_size",
        "_text_detail_mask",
        "_candidate_evidence",
        "_has_candidate_shape_evidence",
        "_has_solid_dark_template_evidence",
        "_has_regular_template_evidence",
        "_has_polarity_background_conflict",
        "_estimate_best_fit",
        "_demix_patch",
        "_apply_watermark_model",
        "_watermark_opacity_and_color",
        "_watermark_evidence_delta",
        "_has_color_template_match_evidence",
        "_has_low_score_match_evidence",
        "_residual_likelihood_map",
        "_template_color_score",
        "_template_chroma_strength",
        "_template_chroma_delta",
        "_normalized_template_weight",
        "_local_maxima_mask",
        "_ranking_score",
        "_masked_vector_correlation",
        "_masked_normalized_correlation",
        "_shape_correlation",
        "_masked_mean",
        "_debug_mask_ratio",
        "_median_kernel_for",
    ),
    "detection": (
        "WatermarkRemover",
    ),
    "ai_detection": (
        "AIDetectionConfig",
        "AIDetectionResult",
        "AIDetectorUnavailableError",
        "Sam3TextWatermarkDetector",
        "DEFAULT_SAM3_MODELSCOPE_MODEL",
        "DEFAULT_SAM3_MODELSCOPE_FILE",
        "download_ai_models",
        "download_sam3_model",
    ),
}

for _module_name, _names in _EXPORTS.items():
    _module = import_module(f"{__package__}.{_module_name}")
    for _name in _names:
        globals()[_name] = getattr(_module, _name)

__all__ = sorted(
    _name
    for _names in _EXPORTS.values()
    for _name in _names
    if not _name.startswith("_")
)
